# Generated by Django 5.0.14 on 2026-08-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_income_donation'),
        ('madrassa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='fee_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='madrassa.feepayment'),
        ),
    ]
