# Generated by Django 5.0.14 on 2026-08-03 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('finance', '0001_initial'),
        ('members', '0002_alter_member_email_alter_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='finance.fund'),
        ),
        migrations.AddField(
            model_name='donation',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='members.member'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.donationtype'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='donation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='donations.donationtype'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='members.member'),
        ),
    ]
