# Generated by Django 5.0.14 on 2026-08-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='bank name')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='bank account')),
                ('bank_iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('hijri_offset', models.IntegerField(default=0, help_text='Days offset used by HIJRI helpers (store Gregorian dates in v1).')),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('setup_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'mosque profile',
                'verbose_name_plural': 'mosque profiles',
            },
        ),
    ]
